# linear and angular speed limits for the robot
# former min vx min vw 
max_v: 0.3 #0.2 #0.4 # m/s
max_w: 0.6 #0.4 #0.8 # rad/s
# observation rate fo the robot
frame_rate: 3 # 10 #30 # Hz
graph_rate: 0.3333 # Hz  

# topic names (modify for different robots/nodes)
vel_teleop_topic: /teleop/cmd_vel #/cmd_vel_mux/input/teleop 
vel_navi_topic:  /former_base_controller/cmd_vel #/move_base/cmd_vel #/cmd_vel_mux/input/navi
vel_recovery_topic: /cmd_vel_mux/input/recovery

deadman_button: 4 # deadman_switch of the joystic
