project_name: devgru-release
#run_name: action_pred #devgru

# training setup
use_wandb: False # set to false if you don't want to log to wandb
train: True
batch_size: 256 # 32 for colldata,  256 for navdata
epochs: 100 #75
gpu_ids: [0]
num_workers: 12
lr: 5e-4
optimizer: adamw
clipping: False
scheduler: "cosine"
warmup: True 
warmup_epochs: 4
seed: 0

# model params
model_type: "devgru_ap" #"devgru_cp" #   #"depth_coll" # 
obs_encoder: "efficientnet-b0" # by default, this is imagenet pretrained
obs_encoding_size: 512
odom_encoding_size: 64
late_fusion: False

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 5

# weight params when computing loss
alpha: 0.9  # tradeoff between action and distance prediction loss
beta: 0.5   # tradoff between orient and waypt prediction (when learn_angle is True)
# distance bounds for distance and action and distance predictions 
distance:
  min_frame_dist: 0
  max_frame_dist: 24
action:
  min_frame_dist: 0
  max_frame_dist: 12
#close_far_threshold: 10 # distance threshold used to seperate the close and the far  subgoals that are sampled per datapoint

goal_dist_type: spatial #temporal

# action output params
len_traj_pred: 5  
learn_angle: True 

# dataset specific parameters
image_size: [85, 64] # width, height
goal_type: depth ##"rgb" # depth

use_time_weight: False #True


# logging stuff
## =0 turns off
#print_log_freq: 100 # in iterations
#image_log_freq: 1000 #0 # in iterations
num_images_log: 24 #16 #8 #0 
pairwise_test_freq: 0 # in epochs
eval_fraction: 0.25
wandb_log_freq: 10 # in iterations
eval_freq: 1 # in epochs

#################################################################
# configs for split_data.py 
#################################################################
data_split:
  split_ratio: 0.8  # (train 0.8, val 0.2)
  former:
    data_folder: /media/data/mydata/former_ewha/mixed_20K
    train: /media/data/mydata/viznav/data_splits/former_ewha/mixed_20K/train
    test:  /media/data/mydata/viznav/data_splits/former_ewha/mixed_20K/test
    waypoint_spacing: 3
    negative_mining: True
#################################################################
# The dataset used for train_action_predictor.py (coll + non-coll data)
#################################################################
datasets:
  former: 
    data_folder: /media/data/mydata/former_ewha/mixed_20K
    train: /media/data/mydata/viznav/data_splits/former_ewha/mixed_20K/train
    test:  /media/data/mydata/viznav/data_splits/former_ewha/mixed_20K/test
    end_slack: 3
    goals_per_obs: 1
    negative_mining: True
    waypoint_spacing: 3 #1      # frame_to_frame spacing  

    
#################################################################
# configs for train_collision_predictor.py 
#################################################################
collision_datasets:
  former:
    data_folder: /media/data/mydata/former_ewha/mixed_20K
    train: /media/data/mydata/viznav/data_splits/former_ewha/mixed_20K/train
    test:  /media/data/mydata/viznav/data_splits/former_ewha/mixed_20K/test
    waypoint_spacing: 3
    
##################################################################
# used for deployment 
##################################################################
deployment:
    dataset_name: former
    topomap_name: T1 #T32 #T1-1 # 
    nav_model_type: devgru_ap #dev_gru
    col_model_type: devgru_cp #depth_coll  # depth_sg_coll
    use_coll_pred_model: True
    goal_type: depth
    waypoint_spacing: 3
    subgoal_spacing: 1  # sg frames to skip (1 skips none, 2 skips 1) 
    xy_dist_thr: 0.5    # meter    
    ang_dist_thr: 5     # deg
    nav_ckpth_name: devgru_ap.pth # devgru-base.pth # #devgru-two_heads-mixed_12K.pth 
    col_ckpth_name: devgru_cp.pth #dev_coll-curr_sg-20K.pth #   
    nav_log_dir: /media/glab/FetchSSD/results/base_lines/devgru
    #ckpth_name: image_pose_rnn-ws3.pth

##################################################################
# used for testing 
##################################################################
test:
    test_dataset_path: /media/data/mydata/former_datasets/colldata/colldata-test
    out_res_path:  /media/results/devgru/devgru_tester/colldata-test/devgru-noncol_08K_col_10K_test-last_dim_32

